#!/usr/bin/env python3
"""Turn ROBOT export/measure output into Markdown pages for mkdocs.

Expects (created by the workflow before this runs):
  docs/generated/terms.csv    <- robot export
  docs/generated/metrics.tsv  <- robot measure (optional)
Writes:
  docs/generated/terms.md
  docs/generated/metrics.md
"""
import csv
import sys
from pathlib import Path

OUT = Path("docs/generated")
NOTE = "<!-- AUTO-GENERATED by src/scripts/generate_docs.py - do not edit by hand -->\n\n"


def cell(value):
    # Keep table cells on one line; multi-values from ROBOT are pipe-separated.
    return (value or "").replace("\r", " ").replace("\n", " ").replace("|", ", ").strip()


def md_table(header, rows):
    lines = ["| " + " | ".join(cell(h) for h in header) + " |",
             "| " + " | ".join("---" for _ in header) + " |"]
    for row in rows:
        row = list(row) + [""] * (len(header) - len(row))
        lines.append("| " + " | ".join(cell(c) for c in row[: len(header)]) + " |")
    return "\n".join(lines) + "\n"


def read(path, delimiter):
    with open(path, newline="", encoding="utf-8") as fh:
        rows = list(csv.reader(fh, delimiter=delimiter))
    return (rows[0], rows[1:]) if rows else ([], [])


def main():
    terms = OUT / "terms.csv"
    if not terms.exists():
        sys.exit(f"missing {terms}")
    header, rows = read(terms, ",")
    label_idx = header.index("LABEL") if "LABEL" in header else 0
    rows.sort(key=lambda r: (r[label_idx] if len(r) > label_idx else "").lower())
    (OUT / "terms.md").write_text(
        NOTE + "# Terms\n\n"
        f"{len(rows)} terms, generated from the current ontology.\n\n"
        + md_table(header, rows),
        encoding="utf-8",
    )

    metrics = OUT / "metrics.tsv"
    if metrics.exists():
        mh, mr = read(metrics, "\t")
        (OUT / "metrics.md").write_text(
            NOTE + "# Ontology metrics\n\n" + md_table(mh, mr), encoding="utf-8"
        )


if __name__ == "__main__":
    main()
